sudo: required

group: deprecated-2017Q3

language: ruby

ruby: 2.4.1

env:
    global:
      - CC_TEST_REPORTER_ID=095bc7916972a84272890f2c79eaba7fd64124a4b5b4e826ba0a4d0599b6bfe3
      - DB=pgsql

services:
  - docker
  - postgresql

install: true

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

test:
  adapter: postgresql
  database: travis_ci_test

addons:
    code_climate:
            repo_token: 095bc7916972a84272890f2c79eaba7fd64124a4b5b4e826ba0a4d0599b6bfe3

notifications:
    slack: gppmds8-github:sJE6QlBfPGMkfUf48wuTsKa7

script:
  - docker-compose -f docker-compose.test.yml up -d
  - docker exec falko-test bash -c "./wait-4-postgres.sh"
  - docker exec falko-test bundle install
  - docker exec falko-test bundle exec rails db:create
  - docker exec falko-test bundle exec rails db:migrate
  - docker exec falko-test bundle exec rake db:test:prepare
  - docker exec falko-test bundle exec rails test
  - docker exec falko-test bash -c "CODECLIMATE_REPO_TOKEN=095bc7916972a84272890f2c79eaba7fd64124a4b5b4e826ba0a4d0599b6bfe3 bundle exec codeclimate-test-reporter"
 
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug
  - docker-compose down --remove-orphans
