version: '3'
services:
  falko-test:
    container_name: falko-test
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: /bin/bash -l -c "./wait-4-postgres.sh && bundle install && RAILS_ENV=test bundle exec rails db:create && RAILS_ENV=test bundle exec rails db:migrate && bundle exec rake db:test:prepare && bundle exec rails test"
    links:
      - falko-server

  falko-database:
    container_name: falko-database
    image: postgres:9.6
    ports: 
      - 5432
    environment:
      - PGDATA=/postgresql
      - PG_USER=postgres
      - PG_DATABASE=travis_ci_test
    volumes:
      - ./tmp/data/postgresql:/postgresql
      - .:/Falko-2017.2-BackEnd

  falko-server:
    container_name: falko-server
    image: alaxalves/api:1.5
    command: /bin/bash -l -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=test
    volumes:
      - .:/Falko-2017.2-BackEnd
    depends_on:
      - falko-database
